/* Generated by Yosys 0.21+23 (git sha1 a9795c4fc, gcc 11.2.0-19ubuntu1 -fPIC -Os) */

(* cells_not_processed =  1  *)
(* src = "adder8.v:1.1-5.10" *)
module adder8(\a[0] , \a[1] , \a[2] , \a[3] , \a[4] , \a[5] , \a[6] , \a[7] , \b[0] , \b[1] , \b[2] , \b[3] , \b[4] , \b[5] , \b[6] , \b[7] , \y[0] , \y[1] , \y[2] , \y[3] , \y[4] 
, \y[5] , \y[6] , \y[7] );
  (* src = "adder8.v:3.12-3.15|fa_map.v:26.44-26.77" *)
  wire ins_00_;
  (* src = "adder8.v:3.12-3.15|fa_map.v:26.44-26.77" *)
  wire ins_01_;
  (* src = "adder8.v:3.12-3.15|fa_map.v:26.44-26.77" *)
  wire ins_02_;
  (* src = "adder8.v:3.12-3.15|fa_map.v:26.44-26.77" *)
  wire ins_03_;
  (* src = "adder8.v:3.12-3.15|fa_map.v:26.44-26.77" *)
  wire ins_04_;
  (* src = "adder8.v:3.12-3.15|fa_map.v:26.44-26.77" *)
  wire ins_05_;
  (* src = "adder8.v:3.12-3.15|fa_map.v:26.44-26.77" *)
  wire ins_06_;
  (* src = "adder8.v:3.12-3.15|fa_map.v:26.44-26.77" *)
  wire ins_07_;
  wire ins_08_;
  wire ins_09_;
  wire ins_10_;
  wire ins_11_;
  wire ins_12_;
  wire ins_13_;
  wire ins_14_;
  wire ins_15_;
  wire ins_16_;
  (* src = "adder8.v:1.27-1.28" *)
  input \a[0] ;
  wire \a[0] ;
  (* src = "adder8.v:1.27-1.28" *)
  input \a[1] ;
  wire \a[1] ;
  (* src = "adder8.v:1.27-1.28" *)
  input \a[2] ;
  wire \a[2] ;
  (* src = "adder8.v:1.27-1.28" *)
  input \a[3] ;
  wire \a[3] ;
  (* src = "adder8.v:1.27-1.28" *)
  input \a[4] ;
  wire \a[4] ;
  (* src = "adder8.v:1.27-1.28" *)
  input \a[5] ;
  wire \a[5] ;
  (* src = "adder8.v:1.27-1.28" *)
  input \a[6] ;
  wire \a[6] ;
  (* src = "adder8.v:1.27-1.28" *)
  input \a[7] ;
  wire \a[7] ;
  (* src = "adder8.v:1.42-1.43" *)
  input \b[0] ;
  wire \b[0] ;
  (* src = "adder8.v:1.42-1.43" *)
  input \b[1] ;
  wire \b[1] ;
  (* src = "adder8.v:1.42-1.43" *)
  input \b[2] ;
  wire \b[2] ;
  (* src = "adder8.v:1.42-1.43" *)
  input \b[3] ;
  wire \b[3] ;
  (* src = "adder8.v:1.42-1.43" *)
  input \b[4] ;
  wire \b[4] ;
  (* src = "adder8.v:1.42-1.43" *)
  input \b[5] ;
  wire \b[5] ;
  (* src = "adder8.v:1.42-1.43" *)
  input \b[6] ;
  wire \b[6] ;
  (* src = "adder8.v:1.42-1.43" *)
  input \b[7] ;
  wire \b[7] ;
  (* src = "adder8.v:1.58-1.59" *)
  output \y[0] ;
  wire \y[0] ;
  (* src = "adder8.v:1.58-1.59" *)
  output \y[1] ;
  wire \y[1] ;
  (* src = "adder8.v:1.58-1.59" *)
  output \y[2] ;
  wire \y[2] ;
  (* src = "adder8.v:1.58-1.59" *)
  output \y[3] ;
  wire \y[3] ;
  (* src = "adder8.v:1.58-1.59" *)
  output \y[4] ;
  wire \y[4] ;
  (* src = "adder8.v:1.58-1.59" *)
  output \y[5] ;
  wire \y[5] ;
  (* src = "adder8.v:1.58-1.59" *)
  output \y[6] ;
  wire \y[6] ;
  (* src = "adder8.v:1.58-1.59" *)
  output \y[7] ;
  wire \y[7] ;
  BUFX2 ins_17_ (
    .A(\a[6] ),
    .Y(ins_06_)
  );
  BUFX2 ins_18_ (
    .A(\a[5] ),
    .Y(ins_05_)
  );
  BUFX2 ins_19_ (
    .A(\a[4] ),
    .Y(ins_04_)
  );
  BUFX2 ins_20_ (
    .A(\a[3] ),
    .Y(ins_03_)
  );
  BUFX2 ins_21_ (
    .A(\a[2] ),
    .Y(ins_02_)
  );
  BUFX2 ins_22_ (
    .A(\a[1] ),
    .Y(ins_01_)
  );
  BUFX2 ins_23_ (
    .A(\a[0] ),
    .Y(ins_00_)
  );
  BUFX2 ins_24_ (
    .A(\a[7] ),
    .Y(ins_07_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "adder8.v:3.12-3.15|fa_map.v:40.18-45.27" *)
  FAX1 ins_25_ (
    .A(\b[1] ),
    .B(ins_01_),
    .C(ins_08_),
    .YC(ins_09_),
    .YS(\y[1] )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "adder8.v:3.12-3.15|fa_map.v:40.18-45.27" *)
  FAX1 ins_26_ (
    .A(\b[2] ),
    .B(ins_02_),
    .C(ins_09_),
    .YC(ins_10_),
    .YS(\y[2] )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "adder8.v:3.12-3.15|fa_map.v:40.18-45.27" *)
  FAX1 ins_27_ (
    .A(\b[3] ),
    .B(ins_03_),
    .C(ins_10_),
    .YC(ins_11_),
    .YS(\y[3] )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "adder8.v:3.12-3.15|fa_map.v:40.18-45.27" *)
  FAX1 ins_28_ (
    .A(\b[4] ),
    .B(ins_04_),
    .C(ins_11_),
    .YC(ins_12_),
    .YS(\y[4] )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "adder8.v:3.12-3.15|fa_map.v:40.18-45.27" *)
  FAX1 ins_29_ (
    .A(\b[5] ),
    .B(ins_05_),
    .C(ins_12_),
    .YC(ins_13_),
    .YS(\y[5] )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "adder8.v:3.12-3.15|fa_map.v:40.18-45.27" *)
  FAX1 ins_30_ (
    .A(\b[6] ),
    .B(ins_06_),
    .C(ins_13_),
    .YC(ins_14_),
    .YS(\y[6] )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "adder8.v:3.12-3.15|fa_map.v:40.18-45.27" *)
  FAX1 ins_31_ (
    .A(\b[7] ),
    .B(ins_07_),
    .C(ins_14_),
    .YC(ins_15_),
    .YS(\y[7] )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "adder8.v:3.12-3.15|fa_map.v:32.14-37.23" *)
  FAX1 ins_32_ (
    .A(\b[0] ),
    .B(ins_00_),
    .C(ins_16_),
    .YC(ins_08_),
    .YS(\y[0] )
  );
  TIELO ins_33_ (
    .Y(ins_16_)
  );
endmodule
