/* Generated by Yosys 0.9+4081 (git sha1 c6681508, gcc 9.3.0-17ubuntu1~20.04 -fPIC -Os) */

(* cells_not_processed =  1  *)
(* src = "adder8.v:1.1-5.10" *)
module adder8(\a[0] , \a[1] , \a[2] , \a[3] , \a[4] , \a[5] , \a[6] , \a[7] , \b[0] , \b[1] , \b[2] , \b[3] , \b[4] , \b[5] , \b[6] , \b[7] , \y[0] , \y[1] , \y[2] , \y[3] , \y[4] , \y[5] , \y[6] , \y[7] );
  (* src = "adder8.v:3.12-3.15|fa_map.v:26.44-26.77" *)
  wire _00_;
  (* src = "adder8.v:3.12-3.15|fa_map.v:26.44-26.77" *)
  wire _01_;
  (* src = "adder8.v:3.12-3.15|fa_map.v:26.44-26.77" *)
  wire _02_;
  (* src = "adder8.v:3.12-3.15|fa_map.v:26.44-26.77" *)
  wire _03_;
  (* src = "adder8.v:3.12-3.15|fa_map.v:26.44-26.77" *)
  wire _04_;
  (* src = "adder8.v:3.12-3.15|fa_map.v:26.44-26.77" *)
  wire _05_;
  (* src = "adder8.v:3.12-3.15|fa_map.v:26.44-26.77" *)
  wire _06_;
  (* src = "adder8.v:3.12-3.15|fa_map.v:26.44-26.77" *)
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  (* src = "adder8.v:1.27-1.28" *)
  input \a[0] ;
  (* src = "adder8.v:1.27-1.28" *)
  input \a[1] ;
  (* src = "adder8.v:1.27-1.28" *)
  input \a[2] ;
  (* src = "adder8.v:1.27-1.28" *)
  input \a[3] ;
  (* src = "adder8.v:1.27-1.28" *)
  input \a[4] ;
  (* src = "adder8.v:1.27-1.28" *)
  input \a[5] ;
  (* src = "adder8.v:1.27-1.28" *)
  input \a[6] ;
  (* src = "adder8.v:1.27-1.28" *)
  input \a[7] ;
  (* src = "adder8.v:1.42-1.43" *)
  input \b[0] ;
  (* src = "adder8.v:1.42-1.43" *)
  input \b[1] ;
  (* src = "adder8.v:1.42-1.43" *)
  input \b[2] ;
  (* src = "adder8.v:1.42-1.43" *)
  input \b[3] ;
  (* src = "adder8.v:1.42-1.43" *)
  input \b[4] ;
  (* src = "adder8.v:1.42-1.43" *)
  input \b[5] ;
  (* src = "adder8.v:1.42-1.43" *)
  input \b[6] ;
  (* src = "adder8.v:1.42-1.43" *)
  input \b[7] ;
  (* src = "adder8.v:1.58-1.59" *)
  output \y[0] ;
  (* src = "adder8.v:1.58-1.59" *)
  output \y[1] ;
  (* src = "adder8.v:1.58-1.59" *)
  output \y[2] ;
  (* src = "adder8.v:1.58-1.59" *)
  output \y[3] ;
  (* src = "adder8.v:1.58-1.59" *)
  output \y[4] ;
  (* src = "adder8.v:1.58-1.59" *)
  output \y[5] ;
  (* src = "adder8.v:1.58-1.59" *)
  output \y[6] ;
  (* src = "adder8.v:1.58-1.59" *)
  output \y[7] ;
  BUFX2 _17_ (
    .A(\b[6] ),
    .Y(_06_)
  );
  BUFX2 _18_ (
    .A(\b[5] ),
    .Y(_05_)
  );
  BUFX2 _19_ (
    .A(\b[4] ),
    .Y(_04_)
  );
  BUFX2 _20_ (
    .A(\b[3] ),
    .Y(_03_)
  );
  BUFX2 _21_ (
    .A(\b[2] ),
    .Y(_02_)
  );
  BUFX2 _22_ (
    .A(\b[1] ),
    .Y(_01_)
  );
  BUFX2 _23_ (
    .A(\b[0] ),
    .Y(_00_)
  );
  BUFX2 _24_ (
    .A(\b[7] ),
    .Y(_07_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "adder8.v:3.12-3.15|fa_map.v:63.18-68.27" *)
  FAX1 _25_ (
    .A(\a[1] ),
    .B(_01_),
    .C(_08_),
    .YC(_09_),
    .YS(\y[1] )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "adder8.v:3.12-3.15|fa_map.v:63.18-68.27" *)
  FAX1 _26_ (
    .A(\a[2] ),
    .B(_02_),
    .C(_09_),
    .YC(_10_),
    .YS(\y[2] )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "adder8.v:3.12-3.15|fa_map.v:63.18-68.27" *)
  FAX1 _27_ (
    .A(\a[3] ),
    .B(_03_),
    .C(_10_),
    .YC(_11_),
    .YS(\y[3] )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "adder8.v:3.12-3.15|fa_map.v:63.18-68.27" *)
  FAX1 _28_ (
    .A(\a[4] ),
    .B(_04_),
    .C(_11_),
    .YC(_12_),
    .YS(\y[4] )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "adder8.v:3.12-3.15|fa_map.v:63.18-68.27" *)
  FAX1 _29_ (
    .A(\a[5] ),
    .B(_05_),
    .C(_12_),
    .YC(_13_),
    .YS(\y[5] )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "adder8.v:3.12-3.15|fa_map.v:63.18-68.27" *)
  FAX1 _30_ (
    .A(\a[6] ),
    .B(_06_),
    .C(_13_),
    .YC(_14_),
    .YS(\y[6] )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "adder8.v:3.12-3.15|fa_map.v:63.18-68.27" *)
  FAX1 _31_ (
    .A(\a[7] ),
    .B(_07_),
    .C(_14_),
    .YC(_15_),
    .YS(\y[7] )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "adder8.v:3.12-3.15|fa_map.v:55.14-60.23" *)
  FAX1 _32_ (
    .A(\a[0] ),
    .B(_00_),
    .C(_16_),
    .YC(_08_),
    .YS(\y[0] )
  );
  BUFX2 _33_ (
    .Y(_16_)
  );
endmodule
