/* Generated by Yosys 0.21+23 (git sha1 a9795c4fc, gcc 11.2.0-19ubuntu1 -fPIC -Os) */

module LFSR31(clk, rst_an, dout);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  input clk;
  wire clk;
  wire \curstate[10] ;
  wire \curstate[11] ;
  wire \curstate[12] ;
  wire \curstate[13] ;
  wire \curstate[14] ;
  wire \curstate[15] ;
  wire \curstate[16] ;
  wire \curstate[17] ;
  wire \curstate[18] ;
  wire \curstate[19] ;
  wire \curstate[1] ;
  wire \curstate[20] ;
  wire \curstate[21] ;
  wire \curstate[22] ;
  wire \curstate[23] ;
  wire \curstate[24] ;
  wire \curstate[25] ;
  wire \curstate[26] ;
  wire \curstate[27] ;
  wire \curstate[28] ;
  wire \curstate[29] ;
  wire \curstate[2] ;
  wire \curstate[30] ;
  wire \curstate[3] ;
  wire \curstate[4] ;
  wire \curstate[5] ;
  wire \curstate[6] ;
  wire \curstate[7] ;
  wire \curstate[8] ;
  wire \curstate[9] ;
  output dout;
  wire dout;
  wire feedback;
  input rst_an;
  wire rst_an;
  XNOR2X1 _31_ (
    .A(\curstate[30] ),
    .B(\curstate[27] ),
    .Y(feedback)
  );
  DFFSR _32_ (
    .CLK(clk),
    .D(\curstate[15] ),
    .Q(\curstate[16] ),
    .R(rst_an),
    .S(_13_)
  );
  DFFSR _33_ (
    .CLK(clk),
    .D(\curstate[16] ),
    .Q(\curstate[17] ),
    .R(rst_an),
    .S(_12_)
  );
  DFFSR _34_ (
    .CLK(clk),
    .D(\curstate[17] ),
    .Q(\curstate[18] ),
    .R(rst_an),
    .S(_11_)
  );
  DFFSR _35_ (
    .CLK(clk),
    .D(\curstate[18] ),
    .Q(\curstate[19] ),
    .R(rst_an),
    .S(_10_)
  );
  DFFSR _36_ (
    .CLK(clk),
    .D(\curstate[19] ),
    .Q(\curstate[20] ),
    .R(rst_an),
    .S(_09_)
  );
  DFFSR _37_ (
    .CLK(clk),
    .D(\curstate[20] ),
    .Q(\curstate[21] ),
    .R(rst_an),
    .S(_08_)
  );
  DFFSR _38_ (
    .CLK(clk),
    .D(\curstate[21] ),
    .Q(\curstate[22] ),
    .R(rst_an),
    .S(_07_)
  );
  DFFSR _39_ (
    .CLK(clk),
    .D(\curstate[22] ),
    .Q(\curstate[23] ),
    .R(rst_an),
    .S(_06_)
  );
  DFFSR _40_ (
    .CLK(clk),
    .D(\curstate[23] ),
    .Q(\curstate[24] ),
    .R(rst_an),
    .S(_05_)
  );
  DFFSR _41_ (
    .CLK(clk),
    .D(\curstate[24] ),
    .Q(\curstate[25] ),
    .R(rst_an),
    .S(_04_)
  );
  DFFSR _42_ (
    .CLK(clk),
    .D(\curstate[25] ),
    .Q(\curstate[26] ),
    .R(rst_an),
    .S(_03_)
  );
  DFFSR _43_ (
    .CLK(clk),
    .D(\curstate[26] ),
    .Q(\curstate[27] ),
    .R(rst_an),
    .S(_02_)
  );
  DFFSR _44_ (
    .CLK(clk),
    .D(\curstate[27] ),
    .Q(\curstate[28] ),
    .R(rst_an),
    .S(_01_)
  );
  DFFSR _45_ (
    .CLK(clk),
    .D(\curstate[28] ),
    .Q(\curstate[29] ),
    .R(rst_an),
    .S(_00_)
  );
  DFFSR _46_ (
    .CLK(clk),
    .D(\curstate[29] ),
    .Q(\curstate[30] ),
    .R(rst_an),
    .S(_29_)
  );
  DFFSR _47_ (
    .CLK(clk),
    .D(feedback),
    .Q(dout),
    .R(_28_),
    .S(rst_an)
  );
  DFFSR _48_ (
    .CLK(clk),
    .D(dout),
    .Q(\curstate[1] ),
    .R(rst_an),
    .S(_30_)
  );
  DFFSR _49_ (
    .CLK(clk),
    .D(\curstate[1] ),
    .Q(\curstate[2] ),
    .R(rst_an),
    .S(_27_)
  );
  DFFSR _50_ (
    .CLK(clk),
    .D(\curstate[2] ),
    .Q(\curstate[3] ),
    .R(rst_an),
    .S(_26_)
  );
  DFFSR _51_ (
    .CLK(clk),
    .D(\curstate[3] ),
    .Q(\curstate[4] ),
    .R(rst_an),
    .S(_25_)
  );
  DFFSR _52_ (
    .CLK(clk),
    .D(\curstate[4] ),
    .Q(\curstate[5] ),
    .R(rst_an),
    .S(_24_)
  );
  DFFSR _53_ (
    .CLK(clk),
    .D(\curstate[5] ),
    .Q(\curstate[6] ),
    .R(rst_an),
    .S(_23_)
  );
  DFFSR _54_ (
    .CLK(clk),
    .D(\curstate[6] ),
    .Q(\curstate[7] ),
    .R(rst_an),
    .S(_22_)
  );
  DFFSR _55_ (
    .CLK(clk),
    .D(\curstate[7] ),
    .Q(\curstate[8] ),
    .R(rst_an),
    .S(_21_)
  );
  DFFSR _56_ (
    .CLK(clk),
    .D(\curstate[8] ),
    .Q(\curstate[9] ),
    .R(rst_an),
    .S(_20_)
  );
  DFFSR _57_ (
    .CLK(clk),
    .D(\curstate[9] ),
    .Q(\curstate[10] ),
    .R(rst_an),
    .S(_19_)
  );
  DFFSR _58_ (
    .CLK(clk),
    .D(\curstate[10] ),
    .Q(\curstate[11] ),
    .R(rst_an),
    .S(_18_)
  );
  DFFSR _59_ (
    .CLK(clk),
    .D(\curstate[11] ),
    .Q(\curstate[12] ),
    .R(rst_an),
    .S(_17_)
  );
  DFFSR _60_ (
    .CLK(clk),
    .D(\curstate[12] ),
    .Q(\curstate[13] ),
    .R(rst_an),
    .S(_16_)
  );
  DFFSR _61_ (
    .CLK(clk),
    .D(\curstate[13] ),
    .Q(\curstate[14] ),
    .R(rst_an),
    .S(_15_)
  );
  DFFSR _62_ (
    .CLK(clk),
    .D(\curstate[14] ),
    .Q(\curstate[15] ),
    .R(rst_an),
    .S(_14_)
  );
  TIEHI _63_ (
    .Y(_00_)
  );
  TIEHI _64_ (
    .Y(_01_)
  );
  TIEHI _65_ (
    .Y(_02_)
  );
  TIEHI _66_ (
    .Y(_03_)
  );
  TIEHI _67_ (
    .Y(_04_)
  );
  TIEHI _68_ (
    .Y(_05_)
  );
  TIEHI _69_ (
    .Y(_06_)
  );
  TIEHI _70_ (
    .Y(_07_)
  );
  TIEHI _71_ (
    .Y(_08_)
  );
  TIEHI _72_ (
    .Y(_09_)
  );
  TIEHI _73_ (
    .Y(_10_)
  );
  TIEHI _74_ (
    .Y(_11_)
  );
  TIEHI _75_ (
    .Y(_12_)
  );
  TIEHI _76_ (
    .Y(_13_)
  );
  TIEHI _77_ (
    .Y(_14_)
  );
  TIEHI _78_ (
    .Y(_15_)
  );
  TIEHI _79_ (
    .Y(_16_)
  );
  TIEHI _80_ (
    .Y(_17_)
  );
  TIEHI _81_ (
    .Y(_18_)
  );
  TIEHI _82_ (
    .Y(_19_)
  );
  TIEHI _83_ (
    .Y(_20_)
  );
  TIEHI _84_ (
    .Y(_21_)
  );
  TIEHI _85_ (
    .Y(_22_)
  );
  TIEHI _86_ (
    .Y(_23_)
  );
  TIEHI _87_ (
    .Y(_24_)
  );
  TIEHI _88_ (
    .Y(_25_)
  );
  TIEHI _89_ (
    .Y(_26_)
  );
  TIEHI _90_ (
    .Y(_27_)
  );
  TIEHI _91_ (
    .Y(_28_)
  );
  TIEHI _92_ (
    .Y(_29_)
  );
  TIEHI _93_ (
    .Y(_30_)
  );
endmodule
